"""empty message

Revision ID: 2d970db44571
Revises: 4a25da80a496
Create Date: 2024-10-11 22:59:38.796430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d970db44571'
down_revision: Union[str, None] = '4a25da80a496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polloption', 'total_votes')
    op.create_index(op.f('ix_vote_option_id'), 'vote', ['option_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_option_id'), table_name='vote')
    op.add_column('polloption', sa.Column('total_votes', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
