"""empty message

Revision ID: 7b561e13648f
Revises: eee33dfa37af
Create Date: 2024-10-04 18:44:47.792729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b561e13648f'
down_revision: Union[str, None] = 'eee33dfa37af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('is_private', sa.Boolean(), nullable=False))
    op.drop_column('poll', 'is_public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('poll', 'is_private')
    # ### end Alembic commands ###
