"""empty message

Revision ID: c7e1e930e5e6
Revises: 10a17bf636ea
Create Date: 2024-10-05 17:44:05.798438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c7e1e930e5e6'
down_revision: Union[str, None] = '10a17bf636ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('voter_email_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_constraint('vote_option_id_fkey', 'vote', type_='foreignkey')
    op.create_foreign_key(None, 'vote', 'polloption', ['option_id'], ['id'], ondelete='CASCADE')
    op.drop_column('vote', 'voter_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('voter_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.create_foreign_key('vote_option_id_fkey', 'vote', 'polloption', ['option_id'], ['id'])
    op.drop_column('vote', 'voter_email_hash')
    # ### end Alembic commands ###
