"""empty message

Revision ID: eee33dfa37af
Revises: be3e6b9fc9d4
Create Date: 2024-10-04 14:07:49.610676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eee33dfa37af'
down_revision: Union[str, None] = 'be3e6b9fc9d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('is_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll', 'is_public')
    # ### end Alembic commands ###
